In [8]:
import os
import json
import pandas as pd

m_path = os.path.split(os.getcwd())[0]
data_path = os.path.join(m_path, 'data')

def read_json(json_path):
    with open(json_path) as json_file:
        json_data = json.load(json_file)
    return json_data

In [9]:
polymarket_metadata = read_json(os.path.join(m_path, "data/polymarket/metadata.json"))
print(polymarket_metadata)

[{'filename': 'polymarket-price-data-03-12-2024-09-12-2024-1734097171475.csv', 'title': 'Daniel Penny found guilty?', 'category': 'Justice', 'about': ["This market will resolve to 'Yes' if Daniel Penny is found guilty of the charge of Manslaughter or Criminally Negligent Homicide in his ongoing New York Court trial by March 31, 2025, 11:59 PM ET. Otherwise, this market will resolve to 'No'.", "If Daniel Penny ongoing trial is dismissed, ends due to a plea agreement without an admission of guilt, or results in a mistrial without Penny being found guilty of either charge, this market will resolve to 'No'.", 'This market will resolve according to the initial judgment rendered in this case. Any appeals will have no bearing on the resolution of this market.', 'The primary resolution source will be an official judgement delivered by the ruling court; however, other credible reporting may be used.'], 'volume': 246115, 'options': ['Yes', 'No'], 'outcome': 'No', 'minutes_filename': None}, {'filename': 'polymarket-price-data-21-11-2024-13-12-2024-1734097154767.csv', 'title': 'Michel Barnier out as prime minister of France in 2024?', 'category': 'Politics', 'about': ["This market will resolve to “Yes” if Michel Barnier ceases to be the Prime Minister of France for any period of time between November 20, 2024 and December 31, 2024, 11:59 PM ET. Otherwise, this market will resolve to 'No'.", 'The resolution source for this market will be the government of France, however a consensus of credible reporting will also suffice.'], 'volume': 598135, 'options': ['Yes', 'No'], 'outcome': None, 'minutes_filename': 'polymarket-price-data-11-12-2024-13-12-2024-1734099882566.csv'}, {'filename': 'polymarket-price-data-03-12-2024-13-12-2024-1734097139510.csv', 'title': 'South Korean President impeached in 2024?', 'category': 'Politics', 'about': ["This market will resolve to 'Yes' if the President of South Korea, Yoon Suk Yeol, is formally impeached by the South Korean National Assembly by December 31, 2024, 11:59 PM ET. Otherwise, this market will resolve to 'No.'", "For this market to resolve to 'Yes' it is only necessary that the National Assembly propose and approve a motion of impeachment against Yoon Suk Yeol, regardless of whether the Constitutional Court later upholds the impeachment.", 'The primary resolution source for this market is official information from the South Korean government, however a consensus of credible reporting may be used.'], 'volume': 2520183, 'options': ['Yes', 'No'], 'outcome': None, 'minutes_filename': 'polymarket-price-data-11-12-2024-13-12-2024-1734099631129.csv'}, {'filename': 'polymarket-price-data-18-11-2024-08-12-2024-1734097322668.csv', 'title': 'Will Assad remain President of Syria through 2024?', 'category': 'Politics', 'about': ["This market will resolve to 'Yes' if Bashar al-Assad remains the President of Syria without interruption from November 17, 2024 through December 31, 2024, 11:59 PM ET. Otherwise, this market will resolve to 'No'.", 'The resolution source for this market will be the CIA World Factbook page for Syria, currently available at https://www.cia.gov/the-world-factbook/countries/syria/#government. A consensus of credible reporting will also suffice.'], 'volume': 7577896, 'options': ['Yes', 'No'], 'outcome': 'No', 'minutes_filename': None}, {'filename': 'polymarket-price-data-03-12-2024-13-12-2024-1734097949406.csv', 'title': 'Yoon out as president of South Korea in 2024?', 'category': 'Politics', 'about': ["This market will resolve to 'Yes' if Yoon Suk Yeol ceases to be the President of South Korea for any period of time between December 2, 2024 and December 31, 2024, 11:59 PM ET. Otherwise, this market will resolve to 'No'.", 'The resolution source for this market will be a consensus of credible reporting.'], 'volume': 4316720, 'options': ['Yes', 'No'], 'outcome': None, 'minutes_filename': 'polymarket-price-data-11-12-2024-13-12-2024-1734099785147.csv'}, {'filename': 'polymarket-price-data-25-10-2024-13-12-2024-1734098142958.csv', 'title': 'Will >= 2% of votes go to 3rd Party candidates?', 'category': 'Politics', 'about': ["This market will resolve to 'Yes' if third party candidates combined receive 2% or more of the total popular vote (including write-ins) in the 2024 US Presidential Election. Otherwise, this market will resolve to 'No'.", 'Third-party candidates refer to any candidates not running as a Democrat or Republican, including candidates running as independents.', 'This market will resolve based on the percentage of third party candidates out of the total number of votes in the 2024 US Presidential election according to uselectionatlas.org once their dataset includes the certified vote totals for all U.S. States and the District of Columbia. If a recount is initiated before certification, the market will remain open until the recount is completed and the vote is certified. If a recount occurs after uselectionatlas.org has published vote totals based on the final certifications, the recount will not be considered.', 'If there are no outstanding recounts, and electionatlas.org has not published total vote numbers based on the state certified results by December 17, 2024, 12:00 PM ET, this market will resolve according to the total vote numbers from the United States Elections Project (electproject.org). If the United States Elections Project has not published certified vote totals, another credible resolution source will be chosen.'], 'volume': 9259174, 'options': ['Yes', 'No'], 'outcome': None, 'minutes_filename': 'polymarket-price-data-11-12-2024-13-12-2024-1734099989668.csv'}, {'filename': 'polymarket-price-data-12-09-2024-12-11-2024-1734098321876.csv', 'title': 'Popular Vote Winner 2024', 'category': 'Politics', 'about': ["This market will resolve to 'Yes' if this is the candidate who receives the most votes in the 2024 U.S. presidential election, otherwise this market will resolve to 'No.'", 'In case of a tie, this market will resolve in favor of the candidate whose last name comes first in alphabetical order.', 'The resolution source will be an overwhelming consensus of credible reporting as to who is the winner of the popular vote.', 'Note: An update may be made to this market to allow for early expiration if the candidate is definitively no longer in contention for the presidency.'], 'volume': 628163458, 'options': ['Michelle Obama', 'Ron DeSantis', 'Kamala Harris', 'Donald Trump', 'Joe Biden', 'Nikki Haley', 'Vivek Ramaswamy', 'Gavin Newsom', 'Robert F. Kennedy Jr.', 'Chris Christie', 'Hillary Clinton', 'Bernie Sanders', 'AOC', 'Elizabeth Warren', 'Kanye West', 'Other Democrat Politician', 'Other Republican Politician'], 'outcome': 'Donald Trump', 'minutes_filename': None}, {'filename': 'polymarket-price-data-18-11-2024-07-12-2024-1734099053295.csv', 'title': 'Next coin listed on Coinbase?', 'category': 'Cryptocurrency', 'about': ["This market will resolve to 'Yes' if this coin is listed for spot purchase on Coinbase.com before any other coin named in this market. Otherwise, this market will resolve to 'No'.", "If no named coin is listed by December 31, 2024, 11:59 PM ET, this market will resolve to 'No'.", 'Relevant coins are as follows: POPCAT, MOODENG, Pnut, Mog, GOAT, FWOG, BITCOIN, NEIRO', 'The primary resolution source for this market will be Coinbase.com, however a consensus of credible reporting will also be used.'], 'volume': 2009956, 'options': ['$POPCAT', '$Mog', '$Pnut', '$MOODENG', '$NEIRO', '$FWOG', '$BITCOIN', 'None of the above in 2024'], 'outcome': '$MOODENG', 'minutes_filename': None}]

In [30]:
kaggle_smd_path = os.path.join(data_path, "KaggleSMD_01.04.2020", "archive")
metadata = pd.read_csv(os.path.join(kaggle_smd_path, 'symbols_valid_meta.csv'))
metadata

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N
...,...,...,...,...,...,...,...,...,...,...,...,...
8044,Y,ZUO,"Zuora, Inc. Class A Common Stock",N,,N,100.0,N,NaN,ZUO,ZUO,N
8045,Y,ZVO,Zovio Inc. - Common Stock,Q,Q,N,100.0,N,N,NaN,ZVO,N
8046,Y,ZYME,Zymeworks Inc. Common Shares,N,,N,100.0,N,NaN,ZYME,ZYME,N
8047,Y,ZYNE,"Zynerba Pharmaceuticals, Inc. - Common Stock",Q,G,N,100.0,N,N,NaN,ZYNE,N
8048,Y,ZYXI,"Zynex, Inc. - Common Stock",Q,S,N,100.0,N,N,NaN,ZYXI,N

In [55]:
stocks_path = os.path.join(kaggle_smd_path, 'stocks')
stocks_dir = os.listdir(stocks_path)
stocks_dir.sort()
ex_stock = pd.read_csv(os.path.join(stocks_path, stocks_dir[0]))
print('Example file:', stocks_dir[0])
ex_stock_name = str(metadata.loc[metadata['Symbol'] == os.path.splitext(stocks_dir[0])[0], 'Security Name'])
ex_stock_name = ex_stock_name.split('Common Stock', 1)[0].split('0', 1)[-1].strip()
print('Company:', ex_stock_name)
ex_stock

Example file: A.csv
Company: Agilent Technologies, Inc.

,Date,Open,High,Low,Close,Adj Close,Volume
0,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300
1,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100
2,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800
3,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600
4,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200
...,...,...,...,...,...,...,...
5119,2020-03-26,70.000000,74.449997,69.650002,73.720001,73.532867,3267500
5120,2020-03-27,71.550003,73.209999,70.279999,70.910004,70.730003,1829800
5121,2020-03-30,71.059998,73.180000,71.059998,72.669998,72.669998,1486200
5122,2020-03-31,72.339996,72.800003,70.500000,71.620003,71.620003,1822100
5123,2020-04-01,69.470001,70.230003,68.150002,68.919998,68.919998,2173600

In [58]:
etfs_path = os.path.join(kaggle_smd_path, 'etfs')
etfs_dir = os.listdir(etfs_path)
etfs_dir.sort()
ex_etf = pd.read_csv(os.path.join(etfs_path, etfs_dir[0]))
print('Example file:', etfs_dir[0])
ex_etf_name = str(metadata.loc[metadata['Symbol'] == os.path.splitext(etfs_dir[0])[0], 'Security Name'])
ex_etf_name = ex_etf_name.split('ETF', 1)[0].split('2', 1)[-1].strip()
print('ETF:', ex_etf_name)
ex_etf

Example file: AAAU.csv
ETF: Perth Mint Physical Gold

           Date       Open       High    Low      Close  Adj Close  Volume
0    2018-08-15  11.840000  11.840000  11.74  11.740000  11.740000   27300
1    2018-08-16  11.780000  11.800000  11.74  11.740000  11.740000  428400
2    2018-08-17  11.800000  11.820000  11.77  11.820000  11.820000   52400
3    2018-08-20  11.880000  11.910000  11.85  11.900000  11.900000   28700
4    2018-08-21  11.920000  11.950000  11.89  11.930000  11.930000   30600
..          ...        ...        ...    ...        ...        ...     ...
405  2020-03-26  16.450001  16.530001  16.23  16.400000  16.400000  212400
406  2020-03-27  16.350000  16.379999  16.25  16.290001  16.290001  172500
407  2020-03-30  16.290001  16.330000  16.09  16.240000  16.240000  536900
408  2020-03-31  16.000000  16.090000  15.71  15.720000  15.720000  193700
409  2020-04-01  15.740000  16.160000  15.68  15.870000  15.870000  296200

[410 rows x 7 columns]